CREATE ROLE dml_role;
GRANT CONNECT ON DATABASE app_db TO dml_role;

GRANT USAGE ON SCHEMA public TO dml_role;

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA public
TO dml_role;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO dml_role;